"use strict";
let car1 = 'subaru';
let age = 20;
let sportCar = true;
console.log("\nIs car === 'subaru'? I predict True.\n");
console.log(car1 === 'subaru');
console.log("\nIs 'subaru' age greater than or equal to 20? I predict True\n");
console.log(age >= 20);
console.log("\nIs 'subaru' sportCar? I predict True.\n");
console.log(sportCar === true);
console.log("\nIs 'subaru' not equal to toyota? I predict True\n");
console.log(car1 !== 'toyota');
console.log("\nIs 'subaru' age less than or equal to 20? I predict True.\n");
console.log(age <= 20);
console.log("\nIs car !== 'subaru'? I predict false.\n");
console.log(car1 !== 'subaru');
console.log("\nIs 'subaru' age greater than && equal to 20? I predict false\n");
console.log(age > 20 && age === 20);
console.log("\nIs 'subaru' local car? I predict false.\n");
console.log(sportCar !== true);
console.log("\nIs 'subaru' equal to toyota? I predict false\n");
console.log(car1 === 'toyota');
console.log("\nIs 'subaru' age less than && equal to 20? I predict false.\n");
console.log(age < 20 && age === 20);
